export const iceBreakers = [
  "If you could only eat one food for the rest of your life, what is it?",
  "What is the most bizarre dream you've ever had?",
  "Would you rather travel 100 years into the past or 100 years into the future?",
  "What is your absolute biggest pet peeve?",
  "If you won the lottery tomorrow, what is the very first thing you would buy?",
  "What is a movie you can watch over and over without getting tired of it?",
  "If you could have any superpower, but it only worked for 5 minutes a day, what would it be?",
  "What's the most spontaneous thing you've ever done?",
  "What's a hill you're willing to die on?",
  "If you could live anywhere in the world for a year, where would you go?",
  "What's the best concert or live event you've ever been to?",
  "What song always puts you in a good mood?",
  "Are you a morning person or a night owl?",
  "What's your go-to comfort food?",
  "If you could have dinner with anyone, living or dead, who would it be?",
  "What's a skill you'd love to learn this year?",
  "What's the funniest thing that happened to you recently?",
  "Do you believe in love at first sight?",
  "What's your favorite way to spend a rainy day?",
  "If you were a character in a video game, what would your special ability be?",
  "What's the most beautiful place you've ever seen?",
  "What's a book, show, or game you'd recommend to anyone?",
  "What's your hidden talent?",
  "Would you rather explore the ocean or outer space?",
  "What's the kindest thing a stranger has done for you?",
  "If you could instantly become an expert in something, what would it be?",
  "What's your favorite holiday and why?",
  "What's the best advice you've ever received?",
  "If you could relive one day of your life, which would it be?",
  "What's your favorite type of weather?",
  "Are you more of a planner or go-with-the-flow person?",
  "What's a food you hated as a kid but love now?",
  "If you could swap lives with someone for a week, who would it be?",
  "What's the scariest thing you've ever done on purpose?",
  "What's your favorite emoji and why?",
  "If you had a theme song that played when you entered a room, what would it be?",
  "What's something on your bucket list?",
  "What's the best gift you've ever gotten?",
  "Would you rather always tell the truth or always lie?",
  "What's your favorite childhood memory?",
  "If you could only listen to one artist forever, who would it be?",
  "What's a conspiracy theory you find funny even if you don't believe it?",
  "What's the worst fashion trend you ever followed?",
  "If you opened a business tomorrow, what would it be?",
  "What's something small that makes your day better?",
  "Do you prefer texting or calling?",
  "What's your favorite season and why?",
  "If animals could talk, which one would be the rudest?",
  "What's the most interesting job you've ever heard of?",
  "What's a place you've never been but really want to visit?",
  "If you could master any instrument overnight, which one?",
  "What's your guilty pleasure TV show?",
  "Would you rather fight one horse-sized duck or 100 duck-sized horses?",
  "What's the best meal you've ever had?",
  "If you could time travel, would you visit the past or the future first?",
  "What's something you're proud of but don't talk about much?",
  "What's your favorite way to meet new people?",
  "If you had to describe yourself in three words, what would they be?",
  "What's the most useless talent you have?",
  "What's a tradition from your family or culture you love?",
  "If you could invent a holiday, what would people celebrate?",
  "What's the best compliment you've ever received?",
  "What's something you changed your mind about recently?",
  "If you could ask the stranger one question with a guaranteed honest answer, what would you ask?",
  "What's the last thing that made you laugh out loud?",
  "If you had to pick a new first name for yourself, what would it be?",
  "What's a song you secretly know every word to?",
  "Would you rather never use social media again or never watch TV again?",
  "What's the most adventurous thing on your bucket list?",
  "If you could only keep three apps on your phone, which ones?",
  "What's a food combination you love that others find weird?",
  "Who was your childhood hero?",
  "What's the best piece of advice you'd give your younger self?",
  "If you could witness any historical event, which one?",
  "What's your favorite board game or card game?",
  "Do you prefer mountains or beaches?",
  "What's something you're looking forward to this month?",
  "If you had a free day with no obligations, how would you spend it?",
  "What's the most interesting person you've met online?",
  "Would you rather be famous for something embarrassing or unknown forever?",
  "What's a movie that made you cry?",
  "If you could speak any language fluently overnight, which one?",
  "What's your favorite smell?",
  "What's the longest you've binge-watched something in one sitting?",
  "If you could have any animal as a pet (real or mythical), what would you pick?",
  "What's a hobby you'd recommend to a total beginner?",
  "What's the best vacation you've ever taken?",
  "If you could delete one thing from the internet, what would it be?",
  "What's your favorite pizza topping?",
  "Are you team sweet or team savory for breakfast?",
  "What's a quote you live by?",
  "If you could redesign your bedroom with unlimited budget, what's the vibe?",
  "What's the most random fact you know?",
  "Would you rather always be 10 minutes late or 20 minutes early?",
  "What's a song that reminds you of a specific memory?",
  "If you could only wear one color for a year, which color?",
  "What's the nicest thing you've done for someone this week?",
  "What's your favorite way to unwind after a long day?",
  "If you could star in any movie genre, which would it be?",
  "What's something you believed as a kid that turned out to be wrong?",
  "Would you rather have unlimited pizza or unlimited coffee?",
  "What's the best live sports or esports moment you've seen?",
  "If you could switch careers tomorrow with guaranteed success, what would you do?",
  "What's your favorite meme or internet trend right now?",
  "What's a place in your city you'd take a visitor first?",
  "If you could only travel by one mode of transport forever, which?",
  "What's the most thoughtful gift you've given someone?",
  "Do you prefer sunrise or sunset?",
  "What's a fear you've overcome?",
  "If you could add one rule everyone had to follow, what would it be?",
  "What's your favorite thing about where you live?",
  "Would you rather know how you die or when you die?",
  "What's the best prank you've ever pulled or had pulled on you?",
  "If you could have dinner with a fictional character, who?",
  "What's something you're surprisingly good at?",
  "What's your go-to karaoke song?",
  "If you could live in any decade, which one and why?",
  "What's the most beautiful song lyric you've ever heard?",
  "Would you rather always be too hot or too cold?",
  "What's a trend you hope comes back?",
  "If you could instantly fix one world problem, which one?",
  "What's the best thing you've learned from a stranger?",
  "What's your favorite type of cuisine?",
  "If you had to eat only breakfast foods or only dinner foods forever, which?",
  "What's something you wish more people knew about you?",
  "Would you rather explore a haunted house or swim with sharks?",
  "What's the most creative excuse you've ever used?",
  "If you could bring back one discontinued product, what is it?",
  "What's your favorite thing to do on a first date (or would do)?",
  "What's a podcast or YouTube channel you'd recommend?",
  "If you could be any age again for one week, what age?",
  "What's the most underrated movie in your opinion?",
  "Would you rather have perfect memory or forget anything on command?",
  "What's something that always cheers you up?",
  "If you could rename yourself a superhero name, what would it be?",
  "What's the best random conversation you've had with a stranger?",
  "What's your favorite holiday tradition?",
  "If you could only listen to one genre of music forever, which?",
  "What's a small habit that changed your life?",
  "Would you rather never eat dessert again or never eat salty snacks?",
  "What's the coolest thing you've ever built or made?",
  "If you could teleport anywhere right now, where would you go?",
  "What's your favorite way to exercise or stay active?",
  "What's something you're passionate about that surprises people?",
  "If you could have any job for just one day, what would you try?",
  "What's the best street food you've ever had?",
  "Would you rather know every language or play every instrument?",
  "What's a TV show character you relate to most?",
  "If you could outlaw one annoying everyday thing, what would it be?",
  "What's the most memorable compliment a stranger gave you?",
  "What's your favorite ice cream flavor?",
  "If you could spend a day with your future self, what's the first question you'd ask?",
  "What's something you collect or wish you collected?",
  "Would you rather live without music or live without movies?",
  "What's the best thing about meeting people online?",
  "If you could only celebrate one holiday for the rest of your life, which?",
  "What's a challenge you're working on right now?",
  "What's your favorite thing to talk about with new people?",
  "If you could swap talents with anyone for a day, who would it be?",
  "What's the most peaceful place you've ever been?",
  "Would you rather always whisper or always shout?",
  "What's a song you'd play to introduce yourself?",
  "If you had a robot assistant, what would you have it do first?",
  "What's the funniest username or gamertag you've seen?",
  "What's one thing you'd tell someone nervous about video chatting?",
];

export function randomIceBreaker(): string {
  return iceBreakers[Math.floor(Math.random() * iceBreakers.length)];
}
